nameOverride: ""
fullnameOverride: ""

image:
  repository: 192.168.1.241:5000/particles
  tag: latest
  pullPolicy: Always

replicas: 1

service:
  entrypoint: ssh
  type: ClusterIP
  port: 22

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

host: particles.raphaelvanhoffelen.com